x-challenge:
  name: "The Iron Shell"
  icon: "TbBrandPowershell"
  description: |
    # The Iron Shell

    **NICE Work Roles**

    - [Cyber Defense Penetration Tester](https://niccs.cisa.gov/tools/nice-framework)

    **NICE Tasks**

    - [T0047](https://niccs.cisa.gov/tools/nice-framework): Conduct vulnerability scans and recognize vulnerabilities in security systems.
    - [T0231](https://niccs.cisa.gov/tools/nice-framework): Perform penetration testing as required.
    - [T0293](https://niccs.cisa.gov/tools/nice-framework): Analyze encrypted data, encrypted traffic, or cryptographic certificates.
    - [T0697](https://niccs.cisa.gov/tools/nice-framework): Exploit system vulnerabilities to elevate privileges.

    ## Background

    You are a hired hacker who's job is to attack a target within an office environment. You have been given access to the network and need to find the machine, enumerate it for vulnerabilities, and attack it to gain root access to it. If you are too loud, you will get kicked from the target and will have to restart your instance.

    ## Getting Started

    You have 4 objectives:

    1. Enumerate and exploit an exposed web portal. You know there is an entrypoint at `/ping`
    1. Crack `ssh` credentials of a user on the machine.
    1. Gain root access to the machine.
    1. Exfiltrate sensitive files without tripping any alarms.

    You have a provided `wordlist.txt` file located at `http://grader/wordlist`.

    To submit the credentials for the ssh machine, you can navigate to `http://grader/` in a web browser.

    ## System and Tool Credentials

    |system/tool|username|password|
    |-----------|--------|--------|
    |kali|user|password|
    |`target`|TBD|TBD|
    |`grader`|N/A|N/A|

  summary: |
    You have been assigned a target. Your job is to enumerate the target for vulnerabilities and exploit it to gain root access to it. 

  templates:
    flag_1: &flag1_template "fake.bothify('PCCC{flag1_??_####}', letters='ABCDEF0123456789')"
    flag_2: &flag2_template "fake.bothify('PCCC{flag2_??_####}', letters='ABCDEF0123456789')"
    flag_3: &flag3_template "fake.bothify('PCCC{flag3_??_####}', letters='ABCDEF0123456789')"
    flag_4: &flag4_template "fake.bothify('PCCC{flag4_??_####}', letters='ABCDEF0123456789')"

  variables:
    flag_1:
      template: *flag1_template
      default: &flag1_template_default "PCCC{flag1_Satisfied}"
    flag_2:
      template: *flag2_template
      default: &flag2_template_default "PCCC{flag2_Satisfied}"
    flag_3:
      template: *flag3_template
      default: &flag3_template_default "PCCC{flag3_Satisfied}"
    flag_4:
      template: *flag4_template
      default: &flag4_template_default "PCCC{flag4_Satisfied}"

  questions:
    - name: "Question 1"
      body: "Web Portal Exploit Flag"
      placeholder: "PCCC{VALUE}"
      points: 624 # 20%
      answer: *flag1_template_default
      max_attempts: 3

    - name: "Question 2"
      body: "SSH Credential Submission Flag"
      placeholder: "PCCC{VALUE}"
      points: 624 # 20%
      answer: *flag2_template_default
      max_attempts: 3
      
    - name: "Question 3"
      body: "Root Access Flag"
      placeholder: "PCCC{VALUE}"
      points: 936 # 30%
      answer: *flag3_template_default
      max_attempts: 3

    - name: "Question 4"
      body: "Sensitive File Flag"
      placeholder: "PCCC{VALUE}"
      points: 936 # 30%
      answer: *flag4_template_default
      max_attempts: 3

services:
  target:
    build: ./target
    hostname: target
    networks:
      - competitor_net
      - hidden_net

  grader:
    build: ./grader
    hostname: grader
    environment:
      token2: *flag2_template_default
    networks:
      - competitor_net

  flagserver:
    build: ./flagserver
    hostname: flagserver
    environment:
      token1: *flag1_template_default
      token3: *flag3_template_default
      token4: *flag4_template_default
    networks: 
    - hidden_net
    

networks:
  competitor_net:
    # external: true  # Uncomment this line to connect to an existing external network
    internal: true
  hidden_net:
    internal: true