x-challenge:
  name: "Arecibo"
  description: |
    # Arecibo

    As an uncover operative, hijack a satellite's command-and-control interface using MQTT exploits. The end goal is to configure an "observatory" to fire its hidden orbital laser.

    **NICE Work Roles**

    - [Vulnerability Analysis](https://niccs.cisa.gov/tools/nice-framework)
    - [Exploitation Analysis](https://niccs.cisa.gov/tools/nice-framework)

    **NICE Tasks**

    - [T1091](https://niccs.cisa.gov/tools/nice-framework): Conduct and/or support authorized penetration testing on enterprise network assets.
    - [T1118](https://niccs.cisa.gov/tools/nice-framework): Identify vulnerabilities


    ## Background

    ðŸ“¡ Word on the street is that the Arecibo Observatory houses a powerful syndicate planning to destabilize the financial systems of neighboring countries and islands using an Electromagnetic Pulse (EMP). As an undercover operative, your mission is to exploit the Arecibo satellite, which is being targeted for malicious purposes. This engagement is the final test of your loyalty to join their ranks. Blue Team members must ensure the mission fails by implementing appropriate remediation. If done correctly, the adversary will attribute the failure to effective countermeasures.

    ## Objectives
    In this challenge, you will:
    * Learn the MQTT protocol to interact with an active orbital laser.
    * Create scripts and automation to determine the correct angle, coordinates, and verification code.
    * Convert the once-marveled observatory into a weapon.

    ## Getting Started

    For this challenge, tokens are awarded for acquiring each necessary data value needed to fire the laser. Challengers must find:

    * The correct angle to hit the target
    * The target's coordinates
    * The verification key (HMAC)
    * The ability to change the mode of the observatory into attack mode

    **Dashboard**
    You will be provided a live dashboard where you can review additional information and track your status in this operation. This dashboard is called the "ARECIBO UPLINK PANEL" and is crucial to your success in this engagement.

    The panel can be found at `http://satellite.obs:5000`.

    **MQTT Pub/Sub**
    The satellite uses the Message Queuing Telemetry Transport (MQTT) protocol to send and receive commands. The protocol is also used to provide up-to-date status on its operations.

    Pub/Sub communication tools will be extremely useful in this challenge.

    ## Submissions

    **IMPORTANT**: Tokens received are only presented to challengers `once`. As this is a covert operation, our actions must be calculated to avoid detection by the custodians of the observatory.

    ## System and Tool Credentials

    |system/tool|location|
    |-----------|--------|
    |arecibo|`mqtt-broker.obs:1883`|
    |Uplink Panel (Dashboard)|`satellite.obs:5000`|

    ## Note

    Attacking or attempting to gain unauthorized access to challenge platform is forbidden.
  icon: "TbSatellite"
  summary: "As an uncover operative, hijack a satellite's command-and-control interface and fire its hidden orbital laser."
  variables:
    token1:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token1 "PCCC{ARE-111111}"
    token2:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token2 "PCCC{ARE-222222}"
    token3:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token3 "PCCC{ARE-333333}"
    token4:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token4 "PCCC{ARE-444444}"
    token5:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token5 "PCCC{ARE-555555}"
    token6:
      template: "fake.bothify('PCCC{ARE-?#?#??}')"
      default: &token6 "PCCC{ARE-666666}"

  questions:
    - name: Token 1 - Sub-A-Thon
      body: Learn how to configure the observatory by interacting with the satellite/core/control topic.
      answer: *token1
      points: 325
      placeholder: PCCC{ARE-XXXXXX}
      max_attempts: 3

    - name: Token 2 - Attack Mode
      body: Configure the observatory to go into `attack mode` using the correct topic - e.g. satellite/core/<TOPIC>
      answer: *token2
      points: 486
      placeholder: PCCC{ARE-XXXXXX}
      max_attempts: 3

    - name: Token 3 - Angular
      body: Configure the correct angle to reach the target via satellite/core/control (Range 0.0-180.0)
      answer: *token3
      placeholder: PCCC{ARE-XXXXXX}
      points: 1094
      max_attempts: 3

    - name: Token 4 - Return of the HMAC
      body: Obtain the key and submit it for HMAC verification by observing all available topics
      answer: *token4
      placeholder: PCCC{ARE-XXXXXX}
      points: 325
      max_attempts: 3

    - name: Token 5 - Coordinated Effort
      body: Determine the correct angle needed to hit the target using the "dump_coords" command via satellite/core/control
      answer: *token5
      points: 910
      placeholder: PCCC{ARE-XXXXXX}
      max_attempts: 3

    - name: Token 6 - Firing The Laser
      body: ðŸ“¡ Fire the laser beam and complete your mission
      answer: *token6
      placeholder: PCCC{ARE-XXXXXX}
      points: 100
      max_attempts: 3

services:
  mqtt-broker:
    build:
      context: ./mqtt-broker
      dockerfile: Dockerfile
    hostname: mqtt-broker.obs
    networks:
      - competitor_net

  satellite-core:
    build:
      context: ./satellite-core
      dockerfile: Dockerfile
    hostname: satellite.obs
    environment:
      token1: *token1
      token2: *token2
      token3: *token3
      token4: *token4
      token5: *token5
      token6: *token6
      MQTT_BROKER_HOST: mqtt-broker.obs
      MQTT_BROKER_PORT: "1883"
    networks:
      - competitor_net

networks:
  competitor_net:
    internal: true
    # external: true  # Uncomment this line to connect to an existing external network